name: simple_push_notification
description: An extended package for handling firebase push notification service and notification navigation in a simple way.
version: 0.3.1
homepage: https://github.com/sagarkarki99/simple_push_notification
issue_tracker: https://github.com/sagarkarki99/simple_push_notification/issues
platforms:
  android:
  ios:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
